### PR TITLE
fix: validate sponsor URL

### LINKED ISSUE #734: Minor url validation for sponsor field would be useful
refs: https://github.com/microsoft/vscode/issues/150748

Have your extension with `"sponsor": "isidor"`, we nicely render the Sponsor button for this extension, but on clicking on the sponsor button I get the following:

Screenshot 2022-05-31 at 13 54 47
 

Could we introduce some basic URL validation on the vsce side? Some basic check so that confused extension authors detect the problem earlier.

### PR DESCRIPTION
**Pull request by sandy081**
Fixes #734

### CODE REVIEW

**Comment by sandy081** [comment]
CC @isidorn 

Instead of naming just `sponsor`, how about calling this property `sponsorUrl` so that it is more obvious?

**Comment by isidorn** [comment]
@sandy081 `sponsorUrl` works for me.

Naming wise it sort of aligns with the `repository` field that has a `url` field in it.
Screenshot 2022-05-31 at 19 03 50

**Comment by sandy081** [comment]
I like `sponsor` object with `url` property. It can be extended if needed in future.

**Comment by isidorn** [comment]
Cool. Works for me :)

**Pull request merged**
