### PR TITLE
feat: support for yarn 2 and yarn berry (3)

### LINKED ISSUE #517: Support yarn v2
In a repository using yarn 2, `vsce package` will fail trying to enumerate dependencies:

```shell
 ERROR  Command failed: yarn list --prod --json
```

To reproduce, in an extension repository, use:

```shell
yarn set version berry
yarn install
vsce package
```

### PR DESCRIPTION
**Pull request by Khaomi**
This PR is confirmed to work on yarn classic (1), yarn 2 and yarn berry (3).

However due to the limitation of yarn 2 and yarn berry (3)'s cli, it's not possible to filter out devdependencies.

I will mark this PR as draft until someone figure out how to do so, i have been searching for a way to filter it out for a while now and i am too afraid to do massive codebase change.

- [ ] filter out devDependencies

close #517

### CODE REVIEW

**Comment by xhayper** [comment]
@microsoft-github-policy-service agree

**Comment by joaomoreno** [comment]
> However due to the limitation of yarn 2 and yarn berry (3)'s cli, it's not possible to filter out devdependencies.

What is the limitation, exactly?

**Comment by xhayper** [comment]
Currently, the CLI don't have the `list` command, so we move to using `yarn info` which list out dependencies BUT far more limited, we can't filter out devdependencies using `info` command BUT that's the only way to list all dependencies as of right now.

**Comment by xhayper** [comment]
I found out that there's an API for the yarn package manager, i will use it to figure out if we can filter out devdependencies.

https://github.com/yarnpkg/berry/blob/master/packages/plugin-essentials/sources/commands/info.ts

**Comment by xhayper** [comment]
i am having trouble using the API, i don't know how to correctly implement the feature using the yarn api at all, it's too confusing for me to understand.

**Comment by Vap0r1ze** [comment]
I think you could filter them out manually by checking the `package.json` in `cwd`

**Pull request closed without merging**
