### PR TITLE
Prompt the user to up the version number.

### PR DESCRIPTION
**Pull request by waderyan**
This can be confusing to the user and they might not realize they can up the version number.

### CODE REVIEW

**Comment by joaomoreno** [comment]
:+1:

**Comment by JimiC** [comment]
Please do maintainance and delete branch.

**Comment by joaomoreno** [comment]
@JimiC Please don't ping us for things like this.

**Comment by JimiC** [comment]
Sorry but my O.C.D. forced me. :smile:

**Pull request merged**
