### PR TITLE
feat(chore): Added update-notifier

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Included the provision to inform users of the updates in a non-intrusive way.

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
@joaomoreno Thoughts :thinking:

**Comment by joaomoreno** [comment]
VSCE already does this: https://github.com/microsoft/vscode-vsce/blob/master/src/main.ts#L49

**Comment by jamesgeorge007** [comment]
@joaomoreno It seems that the current warning prompt showing up is just plain text. Why not have a similar approach as the case of  `update-notifer` wherein which the content is formatted using packages like `boxen`.

**Comment by jamesgeorge007** [comment]
Just thoughts :thinking:

**Comment by joaomoreno** [comment]
It sounds like bloat to me. Let's keep this simple.

**Pull request closed without merging**
