### PR TITLE
[WIP] Link command implementation

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
As discussed in #78. I only know what are correct paths for `stable` and `insiders` target.

### CODE REVIEW

**Comment by SrTobi** [comment]
What happens when I click uninstall in VSCode?

**Comment by Krzysztof-Cieslak** [comment]
It just removes symlink

**Comment by SrTobi** [comment]
:+1: that's cool

**Comment by stkb** [comment]
It's a bug in vscode, but on Windows, uninstalling a symlinked extension deletes the contents of the target directory! (Just comfirmed on 0.10.8 and 0.10.10-insiders)

**Comment by felixfbecker** [comment]
The path for the alpha build is in `~/.vscode-alpha` and for self-built from source `~/.vscode-oss-dev`

**Comment by joaomoreno** [comment]
Sorry for taking so long to pick this up... We definitely want to do this, but it is now dependant on Microsoft/vscode#3884, so let's wait a bit more until that one is completed.

**Comment by Krzysztof-Cieslak** [comment]
No worries at all. Thanks for all crazy good work! :)

**Pull request closed without merging**
