### PR TITLE
Add flags to support automation in edge cases

### PR DESCRIPTION
**Pull request by joaomoreno**
Closes:

- https://github.com/microsoft/vscode-vsce/issues/700
- https://github.com/microsoft/vscode-vsce/issues/706

### CODE REVIEW

**Review by sandy081 — APPROVED** [review]

**Comment by wandyezj** [comment]
When will this be published in a [vsce version on NPM](https://www.npmjs.com/package/vsce)?

**Comment by felipecrs** [comment]
@joaomoreno to prevent this from happening again, when you have a well-made PR with good commit messages (like this one), you can use the "Rebase and Merge" strategy rather than "Squash and Merge".

**Comment by joaomoreno** [comment]
Awesome as always @felipecrs! I'll create a GH workflow with that PR title validation.

**Comment by felipecrs** [comment]
Np :)

**Pull request merged**
