### PR TITLE
Add Personal Access Token as optional parameter in login command

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
#46. //CC : @joaomoreno @forki

Unfortunately, there are no tests for login command (and it's also bit hard to test it for me by hand), so just hoping it works ;)

### CODE REVIEW

**Comment by forki** [comment]
:heart:

**Comment by joaomoreno** [comment]
Closed and reopened to get the CLA bot working.

**Comment by forki** [comment]
@joaomoreno any technical comments?

**Comment by joaomoreno** [comment]
Absolutely. I will review this now. Build looks good, just need the CLA from you. :+1:

**Comment by joaomoreno** [comment]
Actually, I'm thinking that the better fix for this is just to allow passing in the `pat` as an option to all server related commands, instead of doing it in the login command. That's a better story for automation since it doesn't involve writing to `~/.vsce`.

Let me sketch that up...

**Comment by forki** [comment]
Yes if we could avoid a "login" step altogether that would be even better.

BTW:
https://github.com/ionide/ionide-vscode-paket/blob/master/build.fsx#L139
shows our build script that transpiles a F# addin to javascript and
publishes it on the gallery and github.

**Comment by joaomoreno** [comment]
Very cool.

Closing this PR, let's keep discussing it here though.

I've published `vsce@0.9.0-beta`. You wanna give it a try in your build script? You can get it by running `npm install -g vsce@beta`. Let me know how it goes.

**Comment by forki** [comment]
image

doesn't seem to work with vsce@0.9.0-beta

**Comment by joaomoreno** [comment]
Sure sure? What do you get with `vsce -V`?

**Comment by forki** [comment]
image

**Comment by forki** [comment]
ah. it's still on 0.8.1. 

but the build is installing from beta channel:

image

how can I call the new one?

**Comment by joaomoreno** [comment]
No idea. Forget the beta, I just published 0.9.0, give it a try.

**Comment by forki** [comment]
mhm. it downloads 0.9.0 but still calls 0.8.1 so the error is on my side and I'm just calling wrong version of vcse (seems I have two installed)

**Comment by forki** [comment]
found the correct version. now it works like a charme. thanks a lot

**Comment by joaomoreno** [comment]
Awesome!

**Pull request closed without merging**
