### PR TITLE
feat: support pricing model in the manifest file

### PR DESCRIPTION
**Pull request by prashantvc**
Added the support for extension authors label an extension as `FREE` or `FREE TRIAL`

#748

### CODE REVIEW

**Comment by joaomoreno** [comment]
@sandy081 Could you drive this? Notice the introduction of a new field in `package.json`, which might be more impactful than just vsce (VS Code, docs, etc). We can add it to the July plan if necessary.

**Comment by sandy081** [comment]
Let's plan it for next milestone. It would be nice to also show this info in VS Code.

**Review by ProKashif — APPROVED** [review]
Nice man

**Comment by prashantvc** [comment]
@joaomoreno could merge this change please

**Review by joaomoreno — APPROVED** [review]

**Pull request merged**
