### PR TITLE
feat: add Yarn Berry & pnpm support

### LINKED ISSUE #421: Support pnpm
I tried publishing my extension but recently switched to use [pnpm](https://pnpm.js.org/) instead of npm. `vsce` seems to not support this package manager (does `yarn` even works, very similar to `pnpm`) since it tries to do `npm list --production --parseable --depth=99999` which fails in pnpm projects because of the different handling of dependencies.

Project: https://github.com/muuvmuuv/vscode-sundial

Error:

```
❯ npm list --production --parseable --depth=99999
/Users/marvinheilemann/Development/VSCode/vscode-sundial
/Users/marvinheilemann/Development/VSCode/vscode-sundial/node_modules/dayjs
/Users/marvinheilemann/Development/VSCode/vscode-sundial/node_modules/got
/Users/marvinheilemann/Development/VSCode/vscode-sundial/node_modules/public-ip
/Users/marvinheilemann/Development/VSCode/vscode-sundial/node_modules/suncalc
npm ERR! missing: @sindresorhus/is@^1.0.0, required by got@10.5.5
npm ERR! missing: @szmarczak/http-timer@^4.0.0, required by got@10.5.5
npm ERR! missing: @types/cacheable-request@^6.0.1, required by got@10.5.5
npm ERR! missing: cacheable-lookup@^2.0.0, required by got@10.5.5
npm ERR! missing: cacheable-request@^7.0.1, required by got@10.5.5
npm ERR! missing: decompress-response@^5.0.0, required by got@10.5.5
npm ERR! missing: duplexer3@^0.1.4, required by got@10.5.5
npm ERR! missing: get-stream@^5.0.0, required by got@10.5.5
npm ERR! missing: lowercase-keys@^2.0.0, required by got@10.5.5
npm ERR! missing: mimic-response@^2.0.0, required by got@10.5.5
npm ERR! missing: p-cancelable@^2.0.0, required by got@10.5.5
npm ERR! missing: p-event@^4.0.0, required by got@10.5.5
npm ERR! missing: responselike@^2.0.0, required by got@10.5.5
npm ERR! missing: to-readable-stream@^2.0.0, required by got@10.5.5
npm ERR! missing: type-fest@^0.9.0, required by got@10.5.5
npm ERR! missing: dns-socket@^4.2.0, required by public-ip@4.0.0
npm ERR! missing: got@^9.6.0, required by public-ip@4.0.0
npm ERR! missing: is-ip@^3.1.0, required by public-ip@4.0.0
```

### LINKED ISSUE #517: Support yarn v2
In a repository using yarn 2, `vsce package` will fail trying to enumerate dependencies:

```shell
 ERROR  Command failed: yarn list --prod --json
```

To reproduce, in an extension repository, use:

```shell
yarn set version berry
yarn install
vsce package
```

### PR DESCRIPTION
**Pull request by ivangabriele**
This is a work in progress, far from finished.

Don't be frightened by the diff: the first commit in this PR is a proposal to add Prettier w/ EditorConfig using a config as close as possible to the original coding style. Most of the diff is the result of code linting.

## Related Issues

- Resolve #421
- Resolve #517

### CODE REVIEW

**Comment by ivangabriele** [comment]
@microsoft-github-policy-service agree

**Comment by joaomoreno** [comment]
> proposal to add Prettier w/ EditorConfig

Please remove this, since we don't use prettier in the team nor plan to introduce it. Thanks!

**Comment by mrmckeb** [comment]
Can I help with this PR in any way @ivangabriele? Also very excited to see this land!

**Comment by ivangabriele** [comment]
@mrmckeb Sorry I'm on vacation until the end of this week and I try to "cut" during this period. I'll update my work-in-progress next week and ping you if I need help by then, thank you very much!

**Comment by joaomoreno** [comment]
Closing this as out of scope. As part of our recurring maintenance milestone, we've decided to limit the amount of supported package managers to npm and yarn v1 only.

**Comment by mrmckeb** [comment]
Hi @joaomoreno, would you be open to PRs here?

I definitely understand the burden of supporting multiple package managers, but wanted to note:
- For organizations like ours, where we're building our extension inside of a large monorepo, we can't simply change package manager.
- pnpm is now 2x the installs of Yarn (via the npm registry).

**Comment by aleclarson** [comment]
Bumping this in hopes that the team reconsiders PNPM support.

At the time of writing, PNPM has 28.9k stars versus Yarn's 41.4k. I think it's safe to say that the people have spoken, and PNPM is here to stay.

In addition, if you look at this PR's changes (ignoring the formatting-related ones), they are straight-forward and don't add much in terms of maintenance cost, since the package manager APIs used are extremely stable.

**Pull request closed without merging**
