### PR TITLE
remove win32-ia32

### PR DESCRIPTION
**Pull request by joaomoreno**

### CODE REVIEW

**Review by lszomoru — APPROVED** [review]

**Comment by felipecrs** [comment]
@joaomoreno do you mind providing a bit more context? Does this mean I should stop publishing extensions with this target?

**Comment by nvarner** [comment]
@felipecrs I ran into this as well. For partial context, I found microsoft/vscode#195559.

**Comment by sean-mcmanus** [comment]
@joaomoreno Our C/C++ extension can no longer build our 32-bit vsix. What do you advise?

**Comment by sean-mcmanus** [comment]
@joaomoreno We downgraded to npm version [2.21.1](https://www.npmjs.com/package/@vscode/vsce/v/2.21.1). Let us know if you have a recommendation for when we should stop publishing the 32-bit Windows vsix. Our VS Code requirement is currently 1.67.0 or newer.

**Pull request merged**
