### PR TITLE
feat: Support for yarn workspaces

### LINKED ISSUE #300: Support yarn workspaces
Feature request: support [yarn workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/).

`vsce --yarn` (as of 1.52.0) does not package any of the modules from the root's `node_modules/`.

### PR DESCRIPTION
**Pull request by sebas2day**
Fixes #300

This PR is inspired by #379.

I have included a small yarn workspaces fixture in order to test whether its collecting the files in the right way.

### CODE REVIEW

**Comment by phaumer** [comment]
@sebas2day I am trying this PR for a yarn workspace that has a VS Code extension that uses webpack. However, some packages need to be added from the node_modules as they are read at runtime. So I added this in the .vscodeignore file

```
node_modules/**
../../node_modules/**
!../../node_modules/vscode-jsonrpc/**
!../../node_modules/vscode-languageclient/**
!../../node_modules/vscode-languageserver-protocol/**
!../../node_modules/vscode-languageserver-types/**
!../../node_modules/vscode-nls/**
```

None of these were included. Should that work?

**Comment by sebas2day** [comment]
@phaumer Hmm yes the .vscodeignore file might not fully work as expected. I think it would be good to first merge this PR #418 to make the implementation of .vscodeignore simpler so we can eventually fix it later in this PR

**Comment by sebas2day** [comment]
@joaomoreno Any updates on this?

**Comment by sebas2day** [comment]
Sorry in order to resolve the conflicts with master I had to create another PR (and made it a separate branch this time)
See #493

**Pull request closed without merging**
