### PR TITLE
fix #930 and hopefully pass azure pipeline tests

### LINKED ISSUE #930: [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
This should be able to be fixed by updating the `markdown-it` module to 14.0.0.

Issue: https://github.com/markdown-it/markdown-it/issues/967
Release commit: https://github.com/markdown-it/markdown-it/commit/4949a10120d101bdca48bf1b13f9e790d6f2049e

### PR DESCRIPTION
**Pull request by RobbyCBennett**
I already tried fixing this runtime issue with https://github.com/microsoft/vscode-vsce/pull/937, but that failed some Azure pipeline tests. I don't know why it failed because I can't see the output of the tests. Maybe this will work if I change both package.json and package-lock.json.

### CODE REVIEW

**Review by joaomoreno — CHANGES_REQUESTED** [review]
What azure pipeline tests do you mean exactly? Do you have a link?

**Comment by RobbyCBennett** [comment]
Yes. I assumed it was why my original pull request was closed.

https://github.com/microsoft/vscode-vsce/pull/937/checks

image

I don't see those checks on this pull request.

**Comment by benibenj** [comment]
@RobbyCBennett What node version are you using? We support node up to LTS version

**Comment by RobbyCBennett** [comment]
I had version 22, which was installed with `winget install OpenJS.NodeJS`. I have removed it and installed LTS with `winget install OpenJS.NodeJS.LTS`. That fixed the deprecation warning in vsce.

**Pull request closed without merging**
