### PR TITLE
Added trusted badge providers

### PR DESCRIPTION
**Pull request by mxschmitt**
As mentioned in #212.

### CODE REVIEW

**Comment by joaomoreno** [comment]
@kieferrm Give us your blessing! 👍

**Comment by cimfalab** [comment]
Thank you for adding deepscan.io! I really looked forward to this :+1:

**Comment by mxschmitt** [comment]
Removed due no reaction of the owners and maybe incorrect repository.

**Comment by joaomoreno** [comment]
@mxschmitt Sorry that this got lost. Do you mind reopening it?

**Pull request closed without merging**
