### PR TITLE
Supports repository shorthand

### LINKED ISSUE #489: Repository shorthand
With npm, `package.json` supports a shorthand for GitHub, GitLab, BitBucket, etc.

https://docs.npmjs.com/files/package.json#repository

However, vsce spits out a warning when one of these shorthands is used:

```shell
$ cat package.json | grep repository
    "repository": "github:foo/bar",

$ vsce package
 ERROR  Couldn't detect the repository where this extension is published. The link './LICENSE' will be broken in README.md. Please provide the repository URL in package.json or use the --baseContentUrl and --baseImagesUrl options.
```

It would be nice if vsce would support these shorthands.

### PR DESCRIPTION
**Pull request by wangweixuan**
Fixes the parsing of `repository` field in extension manifests, allowing `repository` shorthand.

I added a dependency `hosted-git-info`, which supports parsing repository shorthands and is developed by npm.

Fixes #489.
See also https://github.com/microsoft/vscode/pull/131293.

### CODE REVIEW

**Comment by wangweixuan** [comment]
Resolved failing tests. Also added a test for `gitlab:` shorthand.

**Comment by joaomoreno** [comment]
Can you please remove the change from `package-lock.json`?

**Comment by joaomoreno** [comment]
Also, can you keep the cosmetic changes in a separate PR?

**Review by joaomoreno — CHANGES_REQUESTED** [review]
☝️

**Comment by wangweixuan** [comment]
Done. @joaomoreno

**Comment by joaomoreno** [comment]
Thanks!

**Pull request merged**
